### ISSUE TITLE
Editar adopciones por parte del particular / shelter (21/03)

### ISSUE THREAD

**Issue by DaviidGilB** [ISPP-LinkedPet/frontend_isppet#14]
**DESARROLLO:**
-PARTICULAR: Si la publicación está en "pendiente", es decir, si aún no ha sido moderada, se mantendrá en pendiente de moderación con los nuevos cambios que haya hecho. Si la publicación estaba ya "aceptada", se cambiará a "pendiente" para que vuelva a ser moderada.
-SHELTER: Una publicación de un shelter se crea directamente en "aceptada" ya que no necesita moderación, por lo que cuando edite una publicación se quedará directamente como "aceptada".

**Comment by rubbuemen** [comment]
He estado 2h 24 min hoy. Mañana continuaré

**Comment by rubbuemen** [comment]
He estado 4h 27 min hoy y no lo he conseguido sacar del todo aunque sí avanzar algo.

**Comment by rubbuemen** [comment]
He estado 1h 30 min. Ya funciona en principio, pendiente de revisar-
